In [4]:
import numpy as np
import pandas as pd
from PIL import Image
import os

In [5]:
df = pd.read_csv('datasets/test.csv')

In [6]:
df.sample(5)

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
8289,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11692,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18883,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5259,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
954,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
os.makedirs('static/test_images' , exist_ok=True)

In [13]:
for index , row in df.iterrows():
    img_array = np.array(row).reshape(28,28).astype('uint8')
    img = Image.fromarray(img_array)
    img.save(f'static/test_images/img_{index}.png')



print("✅ Done! All 28,000 images saved to static/test_images/")

✅ Done! All 28,000 images saved to static/test_images/